# Docs and Info coming soon...

This is very much a work in progress and proof of concept exploration. It is possible it will die on the vine or be transformed to a production implementation based on my findings.